# ... (Keep the OS Hardening and Backend sections exactly as they are) ...

- name: Configure Frontend (Nginx Proxy)
  hosts: frontend
  become: yes
  tasks:
    - name: Install Nginx
      package:
        name: nginx
        state: latest

    - name: Remove default nginx configuration to avoid port conflict
      file:
        path: /etc/nginx/conf.d/default.conf
        state: absent

    - name: Configure Proxy from Port 80 to Backend Port 19999
      copy:
        dest: /etc/nginx/conf.d/proxy.conf
        content: |
          server {
              listen 80;
              server_name _;
              location / {
                  proxy_pass http://{{ groups['backend'][0] }}:19999;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
              }
          }
      notify: Reload Nginx

  handlers:
    - name: Reload Nginx
      service:
        name: nginx
        state: restarted # Use restarted to ensure clean state
