---
- name: OS Hardening for Linux
  hosts: all
  become: yes
  tasks:
    - name: Disable SELinux on Amazon Linux
      selinux:
        state: disabled
      when: ansible_os_family == "RedHat"

    - name: Disable Firewalls
      service:
        name: "{{ (ansible_os_family == 'RedHat') | ternary('firewalld', 'ufw') }}"
        state: stopped
        enabled: no
      ignore_errors: yes

- name: Configure Backend (Netdata)
  hosts: backend
  become: yes
  tasks:
    - name: Install Netdata
      shell: "wget -O /tmp/netdata-kickstart.sh https://get.netdata.cloud/kickstart.sh && sh /tmp/netdata-kickstart.sh --non-interactive"
    
    - name: Ensure Netdata runs on port 19999
      lineinfile:
        path: /etc/netdata/netdata.conf
        regexp: 'default port = '
        line: '    default port = 19999'
      notify: Restart Netdata

  handlers:
    - name: Restart Netdata
      service:
        name: netdata
        state: restarted

- name: Configure Frontend (Nginx Proxy)
  hosts: frontend
  become: yes
  tasks:
    - name: Install Nginx
      package:
        name: nginx
        state: present

    - name: Disable default server block in nginx.conf
      replace:
        path: /etc/nginx/nginx.conf
        regexp: '^\s*server\s*{'
        replace: 'server { # disabled by ansible'
      # This is a bit of a "brute force" fix for Amazon Linux's default config
      ignore_errors: yes

    - name: Remove default conf files
      file:
        path: "/etc/nginx/conf.d/{{ item }}"
        state: absent
      with_items:
        - default.conf
        - virtual.conf

    - name: Configure Proxy from Port 80 to Backend Port 19999
      copy:
        dest: /etc/nginx/conf.d/proxy.conf
        content: |
          server {
              listen 80 default_server;
              server_name _;
              location / {
                  proxy_pass http://{{ groups['backend'][0] }}:19999;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              }
          }
      notify: Reload Nginx

  handlers:
    - name: Reload Nginx
      service:
        name: nginx
        state: restarted
